version: '3.8'

services:
  file-backup:
    build: ./build
    image: ${DOCKER_REGISTRY}file-backup:${DOCKER_TAG:-latest}
    init: true
    restart: unless-stopped
    environment:
      DATA_DIR: "${DATA_DIR:?}"
      ROOT_FOLDER_ID: "${DRIVE_FOLDER_ID:?}"
    volumes:
      - "data:/mnt/data"
      - "backup:/root/backup"

volumes:
  data:
    external: true
    name: "${DATA_VOLUME:?}"
  backup:
    name: "${BACKUP_VOLUME:?}"
